### ISSUE TITLE
При загрузке страницы, карта отображается в виде узкой полоски вверху

### ISSUE THREAD

**Issue by petrovnn** [vitalcrazz/OsmPT_frontend#2]
при зуме роликом мыши происходит то-же самое.
Только ресайз окна перерисовывает canvas карты, и карта становится во всю высоту области, которая для нее предназначена. Браузер - Chromium
http://vitalcrazz.github.io/OsmPT_frontend/
![](http://i.imgur.com/kwVZwrt.png)

**Comment by vitalcrazz** [comment]
Проблема несколько шире.
Использовал один из стандартных шаблонов MDL
Demo: http://www.getmdl.io/templates/dashboard/index.html
Src: https://github.com/google/material-design-lite/tree/master/templates/dashboard

В той демке шаблон грузится нормально.
А у меня сейчас весь шаблон грузится узкой полоской, а потом растягивается на весь экран.
Пока не нашёл причину.
